# Generated by Django 2.1.4 on 2018-12-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
